resources:
  - name: wmanning_repo_1_docker_build_push #make this unique to your > use your first name 
    type: GitRepo 
    configuration:
      gitProvider: Github_wmanning   # replace with your integration, we will use the default SolEngDemo repo
      path: williammanning/pipelines_workshop    # replace with your repository path
      branches:
        include: master

  - name: wmanning_build_info_1_docker_build_push
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: svc_build
      buildNumber: 1

  - name: wmanning_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryHA
      buildName: svc_build
      buildNumber: 1


pipelines:
  - name: wmanning_pipeline_docker_build_push
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: wmanning_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: docker.artifactory-cluster.soleng-us.jfrog.team/wmanning_pipeline
          dockerImageTag: ${run_number}
          inputResources:
            - name: wmanning_repo_1_docker_build_push
          integrations:
            - name: ArtifactoryHA

      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: docker-dev-local #replace with your own Docker repo
          integrations:
            - name: ArtifactoryHA
          inputSteps:
            - name: docker_build

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: wmanning_build_info_1_docker_build_push

      - name: promote_build
        type: PromoteBuild
        configuration:
          targetRepository: docker-prod-local
          includeDependencies: true
          status: Released
          comment: Test
          integrations:
            - name: ArtifactoryHA
          inputResources:
            - name: wmanning_build_info_1_docker_build_push
          outputResources:
            - name: wmanning_promoted_build_info